DROP DATABASE IF EXISTS vad_db;
CREATE DATABASE vad_db;

USE vad_db;

CREATE TABLE view_departments (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  names VARCHAR(100) NOT NULL
);

CREATE TABLE roles (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL NOT NULL,
  department_id INT 
);

CREATE TABLE employees (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_id INT
);
